<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ZingPDF.Templates.LiquidHtml/ZingPDF.Templates.LiquidHtml.csproj" />
    <None Include="invoice.liquid.html" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../tests/TestFiles/font/NotoSans-Regular.ttf" Link="NotoSans-Regular.ttf" CopyToOutputDirectory="PreserveNewest" />
    <None Include="OFL.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
