<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ZingPDF.OCR/ZingPDF.OCR.csproj" />
    <None Include="../../tests/TestFiles/font/NotoSans-Regular.ttf" Link="NotoSans-Regular.ttf" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../GenerateInvoices/OFL.txt" Link="OFL.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
